apiVersion: v2
name: pagopa-ecommerce-helpdesk-commands-service
description: Microservice that handles assistance api for ecommerce with manual operations
type: application
version: 0.29.0
appVersion: 0.28.0
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
